version: '3'
services:
  
  api:
    image: stupoid/strongloop-dev
    ports:
      - 3002:3000
    volumes:
      - .:/usr/src/api
    command: nodemon .

  mysqlDB:
    image: mysql:5.6-alpine
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
    ports:
      - 3306:3306
    volumes:
      - strongloopDev:/var/lib/mysql

volumes:
  strongloopDev:
